name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{github.event.inputs.version}}
          repo_token: "${{ secrets.PAT }}"
          prerelease: false
